#!/usr/bin/env bash

# query action
echo "Please select an action:"
echo "e - export latest hardware build to named hardware builds"
echo "r - rename a hardware version"
echo "l - list exported hardware builds"
read action

case $action in 
    'e')
        read -p "specify the hardware build name: " hardware_version
        mkdir _T_DIR_HW_EXPORT_T_/$hardware_version
        cp _T_DIR_HW_EXPORT_T_/{latest/*,$hardware_version}
        ;;
    'r')
        read -p "specify the hardware build to be renamed: " hardware_version_old
        read -p "specify the new name: " hardware_version_new
        mv _T_DIR_HW_EXPORT_T_/{$hardware_version_old,$hardware_version_new}
        ;;
    'l')
        ls _T_DIR_HW_EXPORT_T_
        ;;
    *)
        echo "Unsupported action '$action'"
        ;;
esac

