#!/usr/bin/env bash

include _T_FILE_MAKE_VARIABLES_T_

##############################
# PROJECT MANAGEMENT
##############################

.PHONY: project
project: ${XIL_PRJ}

${XIL_PRJ}:
	${XIL_TOOL} -mode batch -source ${DIR_SCRIPTS}/_T_SCRIPT_CREATE_PROJECT_T_

.PHONY: read_sources
read_sources:
	${XIL_TOOL} -mode batch -source ${DIR_SCRIPTS}/_T_SCRIPT_READ_SOURCES_T_ ${XIL_PRJ}

.PHONY: open
open:
	${XIL_TOOL} -mode tcl ${XIL_PRJ} -source ${DIR_SCRIPTS}/_T_SCRIPT_SOURCE_HELPERS_T_

.PHONY: open_gui
open_gui:
	${XIL_TOOL} -mode gui ${XIL_PRJ} -source ${DIR_SCRIPTS}/_T_SCRIPT_SOURCE_HELPERS_T_

.PHONY: export_hw
export_hw:
	# TODO
	@echo "target $@ is not supported yet"

.PHONY: xip_ctrl
xip_ctrl: ${XIL_DEBUG_CORE_FILES}

# TODO: export that function to some other script that the code manager
# generates. The guideline is that the code manager must not generate anything
# that again calls the code manager
${DIR_XIPS}/xips_debug_cores_%.tcl: ${DIR_RTL}/%.*
	@m_code_manager hdl xip_ctrl --target $*

.PHONY: xips
xips:	xip_ctrl
	${XIL_TOOL} -mode batch -source ${DIR_SCRIPTS}/_T_SCRIPT_XILINX_IP_GENERATION_T_ ${XIL_PRJ}

.PHONY: xip_export_sim
xip_export_sim:
	@make -C ${DIR_SIM} xip_export_sim

##############################
# LINTING
##############################
# Use the verilator linting function for checking (System)Verilog syntax and 
# style, but don't perform any verilation or compilation.
# All targets refer to linting targets within the sim/makefile because all the 
# verilator options are set up there. So although linting in fact has nothing to 
# do with simulation, it's more convenient and for coding more consistent to do 
# it this way.
#
# For providing additional verilator options (like excluding certain warnings in
# the first place), one can specify these as a string in opts:
# make lint opts="-Wno-STMTDLY -Wno-PINCONNECTEMPTY"

# convenience target to refer to vl_lint
.PHONY: lint
lint:	vl_lint

.PHONY: verilator_lint
verilator_lint:
	@make -C ${DIR_SIM} verilator_lint opts="${opts}"

##############################
# SIMULATION
##############################

.PHONY: verilator_start_gui
verilator_start_gui:
	@make -C ${DIR_SIM} verilator_start_gui

.PHONY: sim
sim:
	@make -C ${DIR_SIM} sim

.PHONY: verilator_sim
# vl_sim:			hls_synth
verilator_sim:
	@make -C ${DIR_SIM} verilator_sim

.PHONY: verilator_build
# vl_build:		hls_synth
verilator_build:
	@make -C ${DIR_SIM} verilator_build

# add direct access to other simulators here
.PHONY: modelsim_sim
modelsim_sim:
	@make -C ${DIR_SIM} modelsim_sim

.PHONY: modelsim_compile
modelsim_compile:
	@make -C ${DIR_SIM} modelsim_compile

##############################
# HW BUILD
##############################

# TODO: needs to depend on hw and sw once sw is implemented
.PHONY: build
build:	project build_hw

.PHONY: build_hw
build_hw:	xips
	${XIL_TOOL} -mode batch -source ${DIR_SCRIPTS}/_T_SCRIPT_BUILD_HW_T_ ${XIL_PRJ}

.PHONY: manage_hw_builds
manage_hw_builds:
	${SHELL} _T_DIR_SCRIPTS_T_/_T_SCRIPT_MANAGE_BUILDS_T_

##############################
# SW BUILD
##############################

.PHONY: sdk_project
sdk_project:
	# TODO
	@echo "target $@ is not supported yet"

.PHONY: build_sw
build_sw:
	# TODO
	@echo "target $@ is not supported yet"

##############################
# EXECUTION
##############################

.PHONY: program_fpga
program_fpga:
	${XIL_TOOL} -mode batch -source ${DIR_SCRIPTS}/_T_SCRIPT_BUILD_HW_T_ \
					-tclargs _T_COMMAND_PROG_FPGA_T_

.PHONY: program_soc
program_soc:
	# TODO
	@echo "target $@ is not supported yet"

.PHONY: program_sw
program_sw:
	# TODO
	@echo "target $@ is not supported yet"

# convenience target - maybe in the future when there are more (elaborated) run 
# options, this one can differentiate and link to something different
.PHONY: run
run: run_hw_ctrl

# start up top level vio hardware control
.PHONY: run_hw_ctrl
run_hw_ctrl:
	${XIL_TOOL} -mode tcl -source ${DIR_SCRIPTS}/_T_SCRIPT_XILINX_VIO_CONTROL_T_
